# Generated by Django 5.2.6 on 2026-04-14 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_create_admin'),
        ('accounts', '0004_alter_user_logo'),
    ]

    operations = [
    ]
